### ISSUE TITLE
Keep Pet Tutor alive

### ISSUE THREAD

**Issue by silhouettes** [PetTutor/PetTutor-SDK-Demos#6]
Is there any way to keep the Pet Tutor on, for example by periodically sending a no-op bluetooth signal to it? I'm working on triggering it from a raspberry pi whenever a sound happens in the hallway outside my apartment, but I think the Pet Tutor may turn itself off if there is no sound for a long duration.

**Comment by smartanimaltraining** [comment]
Plug in an external USB Anker battery(this battery stays on).   If more questions email Support@PetTutor.Biz
